### ISSUE TITLE
typo in SNP encoding ?

### ISSUE THREAD

**Issue by jeanrjc** [flag0010/pop_gen_cnn#4]
Hello,

I think there is a typo here: https://github.com/flag0010/pop_gen_cnn/blob/294a474c4febc019ec42c8979fbd8ead2f01248a/demography/demogConvRegMerge.py#L71

at this step, I believe that values in `X` are either 0 or 255 from here:
https://github.com/flag0010/pop_gen_cnn/blob/294a474c4febc019ec42c8979fbd8ead2f01248a/demography/extractDataSet.py#L30

But using `X.astype('int8')` will convert `255` into `-1` because `int8` is defined between -128 and 127 (`np.int8(255) -> -1`).

So I think there is a typo and one should read `X.astype('uint8')`

**Comment by flag0010** [comment]
Thanks for pointing this out. I believe you are correct, and that this means the encoding was 0/-1 rather than 0/255.  Sorry about any confusion this caused.  

I have given it some thought, and decided to leave this error as is (though add a comment in the code), because I view this repo as a snapshot of what was run in the manuscript rather than as living/changing project.

**Comment by flag0010** [comment]
updated code: https://github.com/flag0010/pop_gen_cnn/commit/3098e68cbe78dca75d937d613ea0269b6e6a9b3a#diff-67bef8651f4f0d5b5a6632b1049779e3
